{{- if .Values.config.providers.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traefik-forward-auth.fullname" . }}-oidc
  labels:
    {{- include "traefik-forward-auth.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.config.providers.oidc.clientSecret | b64enc | quote }}
  client-id: {{ .Values.config.providers.oidc.clientID | b64enc | quote }}
  issuer-url: {{ .Values.config.providers.oidc.issuerUrl | b64enc | quote }}
{{- end }}
