apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traefik-forward-auth.fullname" . }}
  labels:
    {{- include "traefik-forward-auth.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.config.secret | b64enc | quote }}
